In [6]:
%pip install pyarrow
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install scikit-learn
%pip install fastparquet

Collecting pyarrow
  Downloading pyarrow-24.0.0-cp311-cp311-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-24.0.0-cp311-cp311-win_amd64.whl (27.3 MB)
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   ---------- ----------------------------- 7.1/27.3 MB 36.4 MB/s eta 0:00:01
   -------------------- ------------------- 13.9/27.3 MB 33.6 MB/s eta 0:00:01
   -------------------------------- ------- 22.3/27.3 MB 34.4 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.3 MB 32.9 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.3 MB 32.9 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.3 MB 32.9 MB/s eta 0:00:01
   ---------------------------------------- 27.3/27.3 MB 17.6 MB/s  0:00:01
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\lucas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.3.0)
Requirement already satisfied: numpy>=1.23.2 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\lucas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\lucas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from seaborn) (2.3.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from seaborn) (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\lucas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\lucas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting fastparquet
  Downloading fastparquet-2026.3.0-cp311-cp311-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: pandas>=1.5.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fastparquet) (2.3.0)
Requirement already satisfied: numpy in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fastparquet) (2.4.4)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.11.0-cp311-cp311-win_amd64.whl.metadata (681 bytes)
Requirement already satisfied: fsspec in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fastparquet) (2026.3.0)
Requirement already satisfied: packaging in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fastparquet) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2026.3.0-cp311-cp311-win_amd64.whl (669 kB)
   ---------------------------------------- 0.0/669.4 kB ? eta -:--:--
   ---------------------------------------- 669.4/669.4 kB 13.1 MB/s  0:00:00
Downloading cramjam-2.11.0-cp311-cp311-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 18.6 MB/s  0:00:00
Installing collected packages: cramjam, fastparquet

   ---------------------------------------- 0/2 [cramjam]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   -------------------- ------------------- 1/2 [fastparquet]
   ---------------------------------------- 2/2 [fastparquet]

Successfully installed cramjam-2.11.0 fastparquet-2026.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\lucas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd

In [ ]:
df_apontamentos = pd.read_parquet("Base de Dados/datasets/apontamentos/desenvolver_apontamentos.parquet", engine="fastparquet")

In [10]:
df.head()

,Id,Inicio,Fim,Tag,Frota,Tipo,Classe
0,23462554,2025-01-04 19:12:54,2025-01-04 19:40:29,CA65789,793-D 2S,Caminhao,Operando
1,23462555,2025-01-04 19:12:28,2025-01-04 19:38:15,CA65908,793-D 3S,Caminhao,Operando
2,23462556,2025-01-04 19:14:07,2025-01-04 19:18:29,CA65915,793-D 4S,Caminhao,Parado
3,23462759,2025-01-04 19:20:36,2025-01-04 19:27:44,CA5926,793-D 5S,Caminhao,Parado
4,23462762,2025-01-04 19:18:29,2025-01-04 19:23:51,CA65915,793-D 4S,Caminhao,Operando

In [12]:
df_telemetria_abr = pd.read_parquet("Base de Dados/datasets/telemetria/telemetry_abr.parquet", engine="fastparquet")

In [13]:
df_telemetria_abr.head()

,Id_Eventos_Telemetria,Data_Evento,Inicio_Turno,Fim_Turno,Dia,Localidade,TAG,Tag_Frota,Tipo,Nome_Operador_Anon,Matricula_Operador_Hash,Id_Alarme,Alarme,Id_Criticidade,Criticidade,Valor,Classe,Is_Dont_Go
0,52903791,2025-04-01 00:05:34.870,2025-03-31 18:00:00.000,2025-04-01 06:00:00.000,1,Itabira,CA5926,793-D 5S,Caminhao,OP_392,H_5c6a15e253f4,335609934,Rx Channel A Not Receiving Messages,3,Informacional,0,NULL,0
1,52903792,2025-04-01 00:05:34.870,2025-03-31 18:00:00.000,2025-04-01 06:00:00.000,1,Itabira,CA5926,793-D 5S,Caminhao,OP_392,H_5c6a15e253f4,335609935,Rx Channel B Not Receiving Messages,3,Informacional,0,NULL,0
2,52905279,2025-04-01 00:15:37.070,2025-03-31 18:00:00.000,2025-04-01 06:00:00.000,1,Itabira,CA5926,793-D 5S,Caminhao,OP_392,H_5c6a15e253f4,335609935,Rx Channel B Not Receiving Messages,3,Informacional,0,NULL,0
3,52905278,2025-04-01 00:15:37.070,2025-03-31 18:00:00.000,2025-04-01 06:00:00.000,1,Itabira,CA5926,793-D 5S,Caminhao,OP_392,H_5c6a15e253f4,335609934,Rx Channel A Not Receiving Messages,3,Informacional,0,NULL,0
4,52905325,2025-04-01 00:18:36.883,2025-03-31 18:00:00.000,2025-04-01 06:00:00.000,1,Itabira,CA5926,793-D 5S,Caminhao,OP_392,H_5c6a15e253f4,84606980,Transmission Charge Filter - Inactive,3,Informacional,2,Inactive,0